
name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Authenticate with GitHub Packages
      run: |
        dotnet nuget add source \
          --username ${{ secrets.Your_User_Name_Secret }} \
          --password ${{ secrets.Your_Token_Secret }} \
          --store-password-in-clear-text \
          --name github \
          https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Generate Package Version
      id: version
      run: |
        VERSION="1.1.$(date +'%Y%m%d.%H%M%S')"
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Build and Pack
      run: |
        dotnet pack \
          --configuration Release \
          --output ./bin/Release \
          /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Verify Files in bin/Release
      run: ls -al ./bin/Release

    - name: Publish Package to GitHub Packages
      run: |
        dotnet nuget push ./bin/Release/*.nupkg \
          --source github \
          --api-key ${{ secrets.Your_Token_Secret }}
